'use strict';

var LOGGER_TIMEOUT = 30 * 1000;
var STATSD_TIMEOUT = 5 * 1000;
var SHUTDOWN_TIMEOUT = 30 * 1000;
var STATSD_WAIT_PERIOD = 1.5 * 1000;

var INITIAL_STATE = 'initial';
var ON_ERROR_STATE = 'on.error';
var PRE_LOGGING_ERROR_STATE = 'pre.logging.error';
var LOGGING_ERROR_STATE = 'logging.error';
var POST_LOGGING_ERROR_STATE = 'post.logging.error';
var PRE_STATSD_STATE = 'pre.statsd.error';
var STATSD_STATE = 'statsd.error';
var POST_STATSD_STATE = 'post.statsd.error';
var PRE_GRACEFUL_SHUTDOWN_STATE = 'pre.graceful.shutdown';
var GRACEFUL_SHUTDOWN_STATE = 'graceful.shutdown';
var POST_GRACEFUL_SHUTDOWN_STATE = 'post.graceful.shutdown';

module.exports = {
    LOGGER_TIMEOUT: LOGGER_TIMEOUT,
    STATSD_TIMEOUT: STATSD_TIMEOUT,
    SHUTDOWN_TIMEOUT: SHUTDOWN_TIMEOUT,
    STATSD_WAIT_PERIOD: STATSD_WAIT_PERIOD,

    INITIAL_STATE: INITIAL_STATE,
    ON_ERROR_STATE: ON_ERROR_STATE,
    PRE_LOGGING_ERROR_STATE: PRE_LOGGING_ERROR_STATE,
    LOGGING_ERROR_STATE: LOGGING_ERROR_STATE,
    POST_LOGGING_ERROR_STATE: POST_LOGGING_ERROR_STATE,
    PRE_STATSD_STATE: PRE_STATSD_STATE,
    STATSD_STATE: STATSD_STATE,
    POST_STATSD_STATE: POST_STATSD_STATE,
    PRE_GRACEFUL_SHUTDOWN_STATE: PRE_GRACEFUL_SHUTDOWN_STATE,
    GRACEFUL_SHUTDOWN_STATE: GRACEFUL_SHUTDOWN_STATE,
    POST_GRACEFUL_SHUTDOWN_STATE: POST_GRACEFUL_SHUTDOWN_STATE
};
